import { type Analysis, DIMENSIONS, DIMENSION_LABELS, issueCount } from "../components/IssueList";

const FOOTER = `\n---\nGenerated by Website Localization Reviewer\nMAD for Localization Hackathon, June 2026\nTeam: Andrea Danuzzo, Christèle Forget, Gary Hess, Sena Karaca, Estefania Tamayo Pineda`;

function pad(label: string, width = 28) {
  return (label + ":").padEnd(width);
}

export function buildTextReport(
  analysis: Analysis,
  language: string,
  mode: string,
  url: string,
  sourceUrl?: string
): string {
  const date = new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });
  const modeLabel = mode === "mqm" ? "MQM Framework" : mode === "comparison" ? "Comparison" : "AI Judgment";

  const lines: string[] = [
    "WEBSITE LOCALIZATION REVIEW REPORT",
    "===================================",
    `Generated:  ${date}`,
    `Language:   ${language}`,
    `Mode:       ${modeLabel}`,
  ];
  if (url)       lines.push(`Target URL: ${url}`);
  if (sourceUrl) lines.push(`Source URL: ${sourceUrl}`);

  lines.push("", `OVERALL SCORE: ${analysis.overall.score}/10`, analysis.overall.summary);

  lines.push("", "DIMENSION SCORES", "----------------");
  for (const dim of DIMENSIONS) {
    const d = analysis[dim];
    lines.push(`${pad(DIMENSION_LABELS[dim])} ${d.score}/10`);
    lines.push(`  ${d.explanation}`);
  }

  const allIssues = DIMENSIONS.flatMap((dim) =>
    (analysis[dim].issues ?? []).map((issue) => ({ ...issue, dimension: dim }))
  ).sort((a, b) => ({ Critical: 0, Major: 1, Minor: 2 }[a.severity] ?? 3) - ({ Critical: 0, Major: 1, Minor: 2 }[b.severity] ?? 3));

  lines.push("", `FLAGGED ISSUES (${allIssues.length} found)`, "-".repeat(30));
  if (allIssues.length === 0) {
    lines.push("No issues found. The translation appears to meet quality standards.");
  } else {
    for (const issue of allIssues) {
      lines.push(`\n[${issue.severity.toUpperCase()}] ${DIMENSION_LABELS[issue.dimension]}`);
      if (issue.quote) lines.push(`  "${issue.quote}"`);
      lines.push(`  ${issue.note}`);
    }
  }

  lines.push(FOOTER);
  return lines.join("\n");
}

export type MultiRow = { name: string; analysis: Analysis };

export function buildCSV(rows: MultiRow[]): string {
  const header = ["Language", "Overall", "Linguistic Quality", "Terminology Consistency", "Cultural Adaptation", "Completeness", "Total Issues"];
  const dataRows = rows.map((r) => [
    r.name,
    r.analysis.overall.score.toFixed(1),
    r.analysis.linguistic_quality.score.toFixed(1),
    r.analysis.terminology_consistency.score.toFixed(1),
    r.analysis.cultural_adaptation.score.toFixed(1),
    r.analysis.completeness.score.toFixed(1),
    issueCount(r.analysis).toString(),
  ]);
  return [header, ...dataRows].map((row) => row.join(",")).join("\n");
}

export function buildMultiTextReport(rows: MultiRow[], url: string, mode: string): string {
  const date = new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });
  const modeLabel = mode === "mqm" ? "MQM Framework" : "AI Judgment";

  const lines: string[] = [
    "MULTI-LANGUAGE LOCALIZATION REVIEW REPORT",
    "==========================================",
    `Generated:  ${date}`,
    `Mode:       ${modeLabel}`,
    `URL:        ${url}`,
    "",
    "SCORES SUMMARY",
    "-".repeat(70),
    `${"Language".padEnd(16)}${"Overall".padEnd(10)}${"Linguistic".padEnd(13)}${"Terminology".padEnd(14)}${"Cultural".padEnd(12)}${"Complete".padEnd(11)}Issues`,
    "-".repeat(70),
  ];

  for (const r of rows) {
    const a = r.analysis;
    lines.push(
      `${r.name.padEnd(16)}${String(a.overall.score).padEnd(10)}${String(a.linguistic_quality.score).padEnd(13)}${String(a.terminology_consistency.score).padEnd(14)}${String(a.cultural_adaptation.score).padEnd(12)}${String(a.completeness.score).padEnd(11)}${issueCount(a)}`
    );
  }

  for (const r of rows) {
    lines.push("", "=".repeat(70), `${r.name.toUpperCase()} — ${r.analysis.overall.score}/10`, "=".repeat(70));
    lines.push(r.analysis.overall.summary);

    lines.push("", "Dimension Scores", "-".repeat(30));
    for (const dim of DIMENSIONS) {
      const d = r.analysis[dim];
      lines.push(`${pad(DIMENSION_LABELS[dim])} ${d.score}/10`);
      lines.push(`  ${d.explanation}`);
    }

    const allIssues = DIMENSIONS.flatMap((dim) =>
      (r.analysis[dim].issues ?? []).map((issue) => ({ ...issue, dimension: dim }))
    ).sort((a, b) => ({ Critical: 0, Major: 1, Minor: 2 }[a.severity] ?? 3) - ({ Critical: 0, Major: 1, Minor: 2 }[b.severity] ?? 3));

    lines.push("", `Flagged Issues (${allIssues.length})`, "-".repeat(30));
    if (allIssues.length === 0) {
      lines.push("No issues found.");
    } else {
      for (const issue of allIssues) {
        lines.push(`\n[${issue.severity.toUpperCase()}] ${DIMENSION_LABELS[issue.dimension]}`);
        if (issue.quote) lines.push(`  "${issue.quote}"`);
        lines.push(`  ${issue.note}`);
      }
    }
  }

  lines.push(FOOTER);
  return lines.join("\n");
}

export function buildFilename(base: string, ext: string): string {
  const today = new Date().toISOString().slice(0, 10);
  let serial = 1;
  if (typeof window !== "undefined") {
    try {
      const stored = localStorage.getItem("export_serial");
      if (stored) {
        const { date, count } = JSON.parse(stored);
        if (date === today) serial = count + 1;
      }
      localStorage.setItem("export_serial", JSON.stringify({ date: today, count: serial }));
    } catch { /* localStorage unavailable */ }
  }
  return `${base}-${today}-${serial}.${ext}`;
}

export function download(filename: string, content: string, mime: string) {
  const blob = new Blob([content], { type: `${mime};charset=utf-8` });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement("a");
  a.href = url; a.download = filename; a.click();
  URL.revokeObjectURL(url);
}
